name: Spacex Application Deployment Workflow

on: [push]

jobs:
  build:
    - name: Build Job 
        runs-on: ubuntu-latest
        steps:
          - name: Verify the Node.JS Version
          run: node --version-
  
#   build:

#     runs-on: ubuntu-latest
#     steps:
#       - name: Install and Configure Node.JS
#         uses: actions/setup-node@v2
#         with:
#           node-version: "12"
      
#       - name: Verify the Node.JS Version
#         run: node --version

#       - name: Install Gatsby Library
#         run: npm install -g gatsby-cli
#       - name: Checkout the Code
#         uses: actions/checkout@v2

#       - name: Install Node Modules
#         run: npm install

#       - name: Build the Spacex Application using Gatsby
#         run: gatsby build

#       - name: Archive the Build Folder i.e public folder
#         uses: actions/upload-artifact@v2
#         with:
#           name: spacexpublicfolder
#           path: public
#         if: always()

#   deployment:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Download Spacex Application Public Folder
#         uses: actions/download-artifact@v2
#         id: spacexfolderdownload
#         with:
#           name: spacexpublicfolder
#           path: .

#       - name: Display Structure of downloaded files
#         run: ls -R
#         working-directory: .

#       - name: Print the Downloaded Path
#         run: echo ${{steps.spacexfolderdownload.outputs.download-path}}

#       - name: Install Surge
#         run: npm install -g surge

#       - name: Deploying the Application using Surge
#         run: surge . ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

#test
